Implement Training and Saving model in train_model.py
ContriHUB/SecureFace pull request #16
Opened 2023-10-11 04:34 UTC by MauryaRitesh

Implemented training and saving of model in train_model.py.

## Description

Solved TODO 1.

Fixes #3 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):
![Screenshot 2023-10-11 095817](https://github.com/ContriHUB/SecureFace/assets/31176772/0caee9dd-3bd4-474b-899a-39c3f93068f1)

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

2023-10-11 08:07 UTC, sanskaromar requested changes
Please make required changes.

2023-10-11 08:07 UTC, sanskaromar commented on train_model/trained_models/LBPH_face_recognition_model.xml
The naming convention of model name isn't followed.

2023-10-11 08:07 UTC, sanskaromar commented on train_model/label_to_name_mapping.csv
No need for this file. Refer to documentation or README for understanding project structure.

2023-10-11 08:07 UTC, sanskaromar commented on train_model/train_model.py
> +    data_dir = 'train_data'
Did you read the code? This path is already declared above.

2023-10-11 08:07 UTC, sanskaromar commented on train_model/train_model.py
> +    face_recognizer.train(faces, np.array(labels))
I think we can also do `np.array(faces, dtype='object')`

2023-10-11 08:07 UTC, sanskaromar commented on train_model/train_model.py
> +    model_filename = f'trained_models/{algorithm}_face_recognition_model.xml'
Wrong model naming convention. Also, give absolute path `app/trained_model/{filename}`.

2023-10-11 08:07 UTC, sanskaromar commented on train_model/train_model.py
> +    label_to_name_filename = 'label_to_name_mapping.csv'
The file already exists with different name. Read documentation.

2023-10-11 19:25 UTC, MauryaRitesh commented on train_model/train_model.py
> +    label_to_name_filename = 'label_to_name_mapping.csv'
@sanskaromar Sorry, I didn't pay much attention. Can you check now?

2023-10-12 18:10 UTC, sanskaromar approved these changes
🚀

2023-10-12 18:10 UTC, merged