Implemented Test for Facial Recognition
ContriHUB/SecureFace pull request #17
Opened 2023-10-11 05:39 UTC by Aqua-16

## Description

I have imported pytesseract module for the purpose of testing the facial recognition function and its proper labelling. The module is used to check what label has been added to any recognized faces. If the labelling follows the known convention, i.e., 
Name: <person_name>
Authorization Status: <is_authorized>

, then the recognize_face module works properly, given that no other errors arise during its runtime.

## Related Issue
Also somewhat fixes the tester for the logging function.

Fixes #9 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Screenshots (if appropriate):

![image](https://github.com/ContriHUB/SecureFace/assets/123102778/a3c011f4-4eb0-4e52-a384-0cd9518cc879)
The third '.' in '.E.' signifies that there are no errors in recognize_face.

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-10-11 08:25 UTC, sanskaromar requested changes
As discussed, We need to make few changes

2023-10-11 08:25 UTC, sanskaromar commented on tests/test_images/test_face.png
Upload minified jpg images.

2023-10-11 11:44 UTC, Aqua-16 commented on tests/test_images/test_face.png
Done, also added more images

2023-10-11 11:45 UTC, Aqua-16 commented
I have made it check multiple image files and also coded it to generally pull from the image directory instead of hard coding the path, so more images can be added. 

Also, I've not specifically mentioned a model to be used, so testing can be done on any model added to the specified directory.

2023-10-12 18:02 UTC, sanskaromar approved these changes
Good Work 🚀

2023-10-12 18:02 UTC, sanskaromar commented on app/security_system.py
> +            thickness= 5
Nice.

2023-10-12 18:04 UTC, merged

2023-10-12 18:09 UTC, Aqua-16 commented on app/security_system.py
> +            thickness= 5
Thanks 😄